name: Process Bank Address Data

on:
  push:
    branches:
      - main

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flask

      - name: Run Flask API
        run: nohup python scripts/load_data.py &

  deploy_ui:
    runs-on: ubuntu-latest
    needs: process_data
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: static
