name: Data Processing and Geocoding

on:
  push:
    branches: [main, master]

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Or your preferred version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl geopy

      - name: Run data processing script
        run: python scripts/data_processing.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data processing and geocoding"
          file_pattern: data/bank_locations_geocoded.csv data/bank_locations.csv
          push_options: '--force-with-lease'  # Or just '' if you don't need --force-with-lease

      - name: List files (for debugging)
        run: ls -l data
