name: Data Processing and Geocoding

on:
  push:
    branches: [main, master]

jobs:
  process_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl geopy

      - name: Upgrade openpyxl  # The crucial addition
        run: pip install --upgrade openpyxl

      - name: Run data processing script
        run: python scripts/data_processing.py

      - name: Run geocoding script
        run: python scripts/geocoding.py

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data processing and geocoding"
          file_pattern: data/bank_locations_geocoded.csv
          push_options: '--force-with-lease'
