name: Data Processing and Geocoding

on:
  push:
    branches: [main, master]

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Debug: List files before processing
        run: |  # Correct indentation here
          echo "Current Directory: $(pwd)"
          ls -l
          ls -l data/
          file data/detail-implantation-bancaire-2022.xlsx

      - name: Run data processing script
        working-directory: ./scripts
        run: python create_address_json.py  # No need for | here for a single command

      - name: Debug: Verify JSON output
        run: |  # Correct indentation here
          ls -l data/
          cat data/addresses.json

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated data processing and geocoding"
          file_pattern: data/addresses.json
