name: Process Bank Address Data

on:
  push:
    branches: [main, master]
    paths:
      - "data/*.xlsx"  # Trigger only when Excel files are updated
  workflow_dispatch:  # Allows manual triggering

jobs:
  process_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl

      - name: Convert Excel to JSON
        run: python scripts/create_address_json.py

      - name: Commit and push updated JSON
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update: Bank addresses JSON refreshed"
          file_pattern: "data/addresses.json"
